---
- name: Check webserver status
  hosts: all

  sources:
    - ansible.eda.url_check:
        urls:
          - https://web3.ramzidev.com
        delay: 10
  
  rules:
    - name: Site down
      condition: event.url_check.status == 'down'
      action:
        debug:
          msg: "{{ event.url_check.url | ansible.builtin.regex_search('(?:http[s]*\\:\/\/)*(.*?)\\.(?=[^\/]*\\..{2,5})', '\\1') }}"
      
